---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pull-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-pull-creds
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - get
  - create
  - update
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - list
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-pull-creds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-pull-creds
subjects:
- kind: ServiceAccount
  name: image-pull-creds
